version: '3.9'

services:
  app:
    container_name: app
    command: python3 __main__.py
    env_file: .env
    build:
      context: ./app
      dockerfile: app.dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000

  bot:
    container_name: bot
    build: 
      context: ./bot
      dockerfile: bot.dockerfile
    env_file:
      - bot.env
    depends_on:
      - db
    restart: always
    expose:
      - 8081

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/etc-letsencrypt:/etc/letsencrypt
      - ./nginx/www-html:/var/www/html
      - ./front:/etc/nginx/front
      - ./static:/etc/nginx/static_img
    ports:
      - 80:80
      - 443:443

  db:
    container_name: db
    image: postgres:latest
    env_file: db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
